### ISSUE TITLE
gem install 'video-sprites' = no go :'(

### ISSUE THREAD

**Issue by todrobbins** [jronallo/video-sprites#5]
Here's what I'm running:

```
$ gem install 'video-sprites'
ERROR:  Could not find a valid gem 'video-sprites' (>= 0) in any repository
ERROR:  Possible alternatives: video-sprites
```

Tried without quotes:

```
$ gem install video-sprites
ERROR:  Could not find a valid gem 'video-sprites' (>= 0) in any repository
ERROR:  Possible alternatives: video-sprites
```

gem version: 2.0.14
ruby version: ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
ffmpeg version: 2.5.3
montage version: ImageMagick 6.9.0-3 Q16 x86_64 2015-02-10

**Comment by jronallo** [comment]
The gem is only in pre release. See for how to install now. 

https://rubygems.org/gems/video-sprites

Jason

**Comment by todrobbins** [comment]
Thanks for the info Jason. I should have read more carefully.


On Tuesday, February 10, 2015, Jason Ronallo <notifications@github.com>
wrote:

> The gem is only in pre release. See for how to install now.
>
> https://rubygems.org/gems/video-sprites
>
> Jason
>
>
> > On Feb 10, 2015, at 4:20 PM, Tod Robbins <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Here's what I'm running:
> >
> > $ sudo gem install 'video-sprites'
> > ERROR: Could not find a valid gem 'video-sprites' (>= 0) in any
> repository
> > ERROR: Possible alternatives: video-sprites
> > Tried without quotes:
> >
> > $ sudo gem install video-sprites
> > ERROR: Could not find a valid gem 'video-sprites' (>= 0) in any
> repository
> > ERROR: Possible alternatives: video-sprites
> > gem version: 2.0.14
> > ruby version: ruby 2.0.0p481 (2014-05-08 revision 45883)
> [universal.x86_64-darwin14]
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jronallo/video-sprites/issues/5#issuecomment-73816649>
> .
>


-- 
Tod Robbins
Digital Asset Manager, MLIS
todrobbins.com | @todrobbins <http://www.twitter.com/#!/todrobbins>

**Comment by jronallo** [comment]
This should be updated in the README now. @todrobbins Thank you for bringing this to our attention.
